"""Selenium-driven selection integration smoke, not native Recorder acceptance.

Run with PYTHONPATH=. python scripts/smoke_select.py --driver /path/to/msedgedriver.
Artifacts, runtime config and the reusable scenario package stay under build/.
"""

import argparse
import json
from pathlib import Path
from time import monotonic, sleep

from PySide6.QtCore import QCoreApplication, QEvent, QTimer, Qt
from PySide6.QtTest import QTest
from PySide6.QtWidgets import QApplication, QInputDialog, QMessageBox
from selenium.webdriver.support.ui import Select

from flowtape import schema
from flowtape.desktop_dialogs import PageRegistrationDialog
from flowtape.ui import FlowTapeWindow


HOME = 'https://www.uitestingplayground.com/?utm_source=chatgpt.com'
EXPECTED = {
    'selectLanguage': ['Python'],
    'selectCity': ['New York'],
    'selectProduct': ['Release 2.1'],
    'selectColors': ['Red', 'Blue'],
    'selectFruits': ['Banana', 'Date'],
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--driver', required=True)
    parser.add_argument('--artifacts', default='build/select-smoke/acceptance')
    args = parser.parse_args()
    artifacts = Path(args.artifacts).resolve()
    artifacts.mkdir(parents=True, exist_ok=True)
    source = artifacts / 'scenario' / 'scenario.yaml'
    source.parent.mkdir(exist_ok=True)
    config_path = artifacts / 'config.yaml'
    schema.save_yaml(config_path, {
        'version': 1, 'driver': {'path': str(Path(args.driver).resolve())},
        'paths': {name: str(artifacts / name) for name in ('scenarios', 'logs', 'downloads', 'outputs')},
        'credentials': {'path': str(artifacts / 'credentials.yaml')},
    })
    # Navigation is part of the saved scenario, and uses the Player's resolver.
    # Selection steps below are generated by the actual Recorder and GUI.
    schema.save_yaml(source, {'version': 1, 'name': 'Select 選択操作', 'mode': '実行', 'steps': [
        {'action': 'open', 'url': HOME}, {'action': 'click', 'target': 'Select'}]})
    schema.save_yaml(source.with_name('elements.yaml'), {'version': 1, 'pages': {
        'ホーム': {'identify': {'url': {'equals': HOME}}, 'elements': {
            'Select': {'kind': 'link', 'locate': [{'by': 'role', 'role': 'link', 'name': 'Select'}]}}}}})
    app = QApplication.instance() or QApplication([])
    window = FlowTapeWindow(str(source), str(config_path), preferences_path=artifacts / 'preferences.json')
    window.show()
    QTimer.singleShot(0, window.open_browser)
    errors = []
    checks = []

    def wait(predicate, timeout=60):
        deadline = monotonic() + timeout
        while not predicate() and monotonic() < deadline:
            app.processEvents()
            assert not errors, errors
            assert not window.recorder_error, window.recorder_error
            sleep(.02)
        app.processEvents()
        assert predicate(), f'Timed out: {window.status.text()}'
        assert not errors, errors

    def click(button):
        QTest.mouseClick(button, Qt.MouseButton.LeftButton)

    def capture_dialog():
        dialog = app.activeModalWidget()
        if isinstance(dialog, PageRegistrationDialog):
            dialog.validate()
        elif isinstance(dialog, QInputDialog) and dialog.windowTitle() in {'操作の対象', 'Target'}:
            dialog.accept()
        elif isinstance(dialog, QMessageBox):
            errors.append(dialog.windowTitle() + ': ' + dialog.text())
            dialog.accept()

    timer = QTimer()
    timer.setInterval(50)
    timer.timeout.connect(capture_dialog)
    timer.start()

    def playback():
        click(window.play_button)
        wait(lambda: window.worker is not None and not window.worker.isRunning())
        assert window.controller.state == 'complete', str(window.controller.error)

    def selected():
        return {ident: [option.text for option in Select(window.driver.find_element('id', ident)).all_selected_options]
                for ident in EXPECTED}

    try:
        wait(lambda: window.driver is not None)
        playback()
        assert window.driver.current_url == 'https://www.uitestingplayground.com/select'
        checks.append('Player opened the requested homepage and clicked the Select link')
        window.grab().save(str(artifacts / '01-select-page.png'))
        click(window.record_button)
        assert window.recording
        for ident, labels in EXPECTED.items():
            control = Select(window.driver.find_element('id', ident))
            before = len(window.scenario['steps'])
            if control.is_multiple:
                control.deselect_all()
            for label in labels:
                control.select_by_visible_text(label)
            wait(lambda: len(window.scenario['steps']) > before and not window.operation_queue and window.pending_operation is None)
            # All changes must be delivered before selecting the next control.
            wait(lambda: (window.scenario['steps'][-1].get('values') == labels if control.is_multiple
                          else window.scenario['steps'][-1].get('value') == labels[0]))
        assert selected() == EXPECTED, selected()
        click(window.record_button)
        checks.append('Recorder captured three single selections and complete sets for both multi-selects')
        window.actions['保存'].trigger()
        persisted = schema.load_yaml(source)
        registry = schema.load_yaml(source.with_name('elements.yaml'))
        schema.validate_package(persisted, registry)
        assert not window.dirty
        checks.append('GUI saved a valid scenario package')
        # Start with the full saved scenario so preselected fruit and navigation
        # are exercised again. Repeating also verifies stable set replacement.
        for _ in range(2):
            window.restart_playback()
            wait(lambda: window.worker is not None and not window.worker.isRunning())
            assert window.controller.state == 'complete', str(window.controller.error)
            assert selected() == EXPECTED, selected()
        checks.append('Two full GUI/Player replays reached the exact expected sets, removing preselected fruit')
        window.grab().save(str(artifacts / '02-playback-complete.png'))
        window.driver.save_screenshot(str(artifacts / 'edge.png'))
        report = {'checks': checks, 'expected': EXPECTED, 'actual': selected(), 'scenario': str(source),
                  'steps': len(persisted['steps']), 'browser_version': window.driver.capabilities.get('browserVersion'),
                  'public_sites': [HOME, window.driver.current_url], 'errors': errors}
        (artifacts / 'report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
        print(json.dumps(report, ensure_ascii=False, indent=2))
    except Exception as exc:
        window.grab().save(str(artifacts / 'failure.png'))
        (artifacts / 'failure.json').write_text(json.dumps({'error': str(exc), 'checks': checks,
            'status': window.status.text(), 'steps': window.scenario['steps']}, ensure_ascii=False, indent=2), encoding='utf-8')
        raise
    finally:
        timer.stop()
        window.timer.stop()
        if window.worker and window.worker.isRunning():
            window.controller.stop()
            window.worker.wait(3000)
        window.recording = window.picking = False
        window.pending_operation = window.pending_credential = None
        window.operation_queue.clear()
        window.dirty = False
        window.close()
        app.processEvents()
        QCoreApplication.sendPostedEvents(None, QEvent.Type.DeferredDelete)


if __name__ == '__main__':
    main()
